"""update user model for auth

Revision ID: c72712123b7f
Revises: b6108fafac8e
Create Date: 2026-03-14 17:39:03.689831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c72712123b7f'
down_revision: Union[str, None] = 'b6108fafac8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Add the new columns
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    
    # 2. Alter is_active with the USING clause to fix the cast error
    op.alter_column('users', 'is_active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using='is_active::boolean') # <--- Added this line
    
    # 3. Create the index for username
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    
    # When going back, we cast boolean back to integer
    op.alter_column('users', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               postgresql_using='is_active::integer') # <--- Added for safety in downgrade
               
    op.drop_column('users', 'role')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###